foto_index:
    pattern:  /foto/{id}
    defaults: { _controller: AntFotoBundle:Foto:index }
    requirements:
        _method: GET
        id: "\d+"
foto_path:
    pattern: /img/{path}
    defaults: { _controller: AntFotoBundle:Foto:fotoPath }
        
foto_edit:
    pattern:  /foto/{id}
    defaults: { _controller: AntFotoBundle:Foto:editar, _format: ~ }
    requirements:
        _method: PUT
        id: "\d+"
         
publicar_foto:
    pattern: /foto/
    defaults: { _controller: AntFotoBundle:Foto:upload }
    
borrar_foto:
    pattern: /foto/{id}
    defaults: { _controller: AntFotoBundle:Foto:delete }
    requirements:
        _method: DELETE
        id: "\d+"
    
album:
    pattern: /album
    defaults: { _controller: AntFotoBundle:Album:index }
album_amigo:
    pattern: /{username}/album
    defaults: { _controller: AntFotoBundle:Album:indexAmigo }
ant_foto_album_labeled:
    pattern: /{id}/labeled
    defaults: { _controller: AntFotoBundle:Album:labeled }