parameters:
#    foto.example.class: chatea\FotoBundle\Example
    ant_foto.class: chatea\FotoBundle\Entity\Foto

services:
    ant_foto.foto_form.type:
        class: ant\FotoBundle\Form\FotoType
        arguments: [%ant_foto.class%]
